openapi: 3.0.0
info:
  title: Activity Service API
  description: API для управления активностями и их коэффициентами XP
  version: 1.0.0

tags:
  - name: ActivityCommand
    description: API для команд активностей (создание, обновление, удаление)
  - name: ActivityQuery
    description: API для запросов активностей (получение информации)
  - name: UserActivityCommand
    description: API для команд активностей юзера(создание, обновление, удаление)
  - name: UserActivityQuery
    description: API для запросов активностей юзера (получение информации)

paths:
  /activities:
    get:
      summary: Получить список всех активностей
      description: Возвращает все доступные активности
      operationId: getActivities
      tags:
        - ActivityQuery
      responses:
        "200":
          description: Успешный ответ с массивом активностей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ActivityResponseDto"
  /activities/create:
    post:
      summary: Создать новую активность
      description: Добавляет новую активность
      operationId: createActivity
      tags:
        - ActivityCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateActivityRequestDto"
      responses:
        "201":
          description: Активность создана
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateActivityResponseDto"

  /activities/{id}:
    get:
      summary: Получить активность по ID
      description: Возвращает данные об активности
      operationId: getActivityById
      tags:
        - ActivityQuery
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Успешный ответ с активностью
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivityResponseDto"
        "404":
          description: Активность не найдена
    put:
      summary: Обновить активность
      description: Обновляет данные об активности
      operationId: updateActivity
      tags:
        - ActivityCommand
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateActivityRequestDto"
      responses:
        "200":
          description: Активность обновлена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivityResponseDto"
    delete:
      summary: Удалить активность
      description: Удаляет активность по ID
      operationId: deleteActivity
      tags:
        - ActivityCommand
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Активность удалена
  /user-activities/{userId}:
    get:
      summary: Получить активности пользователя
      description: Возвращает список активностей, к которым привязан пользователь
      operationId: getUserActivities
      tags:
        - UserActivityQuery
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Успешный ответ с массивом активностей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserActivityResponseDto"
  /user-activities/create:
    post:
      summary: Добавить активность пользователю
      description: Создает новую запись активности для пользователя
      operationId: addUserActivity
      tags:
        - UserActivityCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserActivityRequestDto"
      responses:
        "200":
          description: Активность успешно добавлена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateUserActivityResponseDto"
        "400":
          description: Неверные входные данные

components:
  schemas:
    ActivityResponseDto:
      type: object
      properties:
        name:
          type: string
          example: coding
        description:
          type: string
          example: Программирование
        category:
          $ref: '#/components/schemas/ActivityCategoryDto'
        unit:
          $ref: '#/components/schemas/ActivityUnitDto'
        baseXp:
          type: integer
          format: int32
          description: Базовый опыт за единицу активности
    CreateActivityRequestDto:
      type: object
      required:
        - name
        - description
        - category
        - unit
        - baseXp
      properties:
        name:
          type: string
          example: coding
        description:
          type: string
          example: Программирование
        category:
          $ref: '#/components/schemas/ActivityCategoryDto'
        unit:
          $ref: '#/components/schemas/ActivityUnitDto'
        baseXp:
          type: number
          format: double
          description: Базовый опыт за единицу активности

    CreateActivityResponseDto:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid

    CreateUserActivityResponseDto:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid

    CreateUserActivityRequestDto:
      type: object
      required:
        - userId
        - activityId
      properties:
        userId:
          type: string
          format: uuid
        activityId:
          type: string
          format: uuid
        customXp:
          type: integer
          description: Пользовательское значение XP

    UserActivityResponseDto:
      type: object
      required:
        - activityId
        - activityName
        - category
        - unit
        - baseXp
      properties:
        activityId:
          type: string
          format: uuid
        activityName:
          type: string
          example: coding
        category:
          $ref: '#/components/schemas/ActivityCategoryDto'
        unit:
          $ref: '#/components/schemas/ActivityUnitDto'
        baseXp:
          type: integer
          format: int32
        customXp:
          type: integer
          description: Пользовательское значение XP

    ActivityUnitDto:
      type: string
      enum:
        - HOURS
        - KILOMETERS
        - SESSIONS
      description: Единица измерения активности

    ActivityCategoryDto:
      type: string
      enum:
        - SPORT
        - EDUCATION
        - HEALTH
        - ENTERTAINMENT
        - OTHER
      description: Категория активности
